In [266]:
# step 1  import libraries
import numpy as np 
import pandas as pd

In [267]:
# step2: Load the dataset
df = pd.read_csv('../data/raw/Telco-Customer-Churn.csv')
print(df.head(10))

   customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService     MultipleLines InternetService OnlineSecurity OnlineBackup DeviceProtection TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling              PaymentMethod  MonthlyCharges TotalCharges Churn
0  7590-VHVEG  Female              0     Yes         No       1           No  No phone service             DSL             No          Yes               No          No          No              No  Month-to-month              Yes           Electronic check           29.85        29.85    No
1  5575-GNVDE    Male              0      No         No      34          Yes                No             DSL            Yes           No              Yes          No          No              No        One year               No               Mailed check           56.95       1889.5    No
2  3668-QPYBK    Male              0      No         No       2          Yes                No             DSL            Yes          Yes               No          No          No              No  Month-to-month              Yes               Mailed check           53.85       108.15   Yes
3  7795-CFOCW    Male              0      No         No      45           No  No phone service             DSL            Yes           No              Yes         Yes          No              No        One year               No  Bank transfer (automatic)           42.30      1840.75    No
4  9237-HQITU  Female              0      No         No       2          Yes                No     Fiber optic             No           No               No          No          No              No  Month-to-month              Yes           Electronic check           70.70       151.65   Yes
5  9305-CDSKC  Female              0      No         No       8          Yes               Yes     Fiber optic             No           No              Yes          No         Yes             Yes  Month-to-month              Yes           Electronic check           99.65        820.5   Yes
6  1452-KIOVK    Male              0      No        Yes      22          Yes               Yes     Fiber optic             No          Yes               No          No         Yes              No  Month-to-month              Yes    Credit card (automatic)           89.10       1949.4    No
7  6713-OKOMC  Female              0      No         No      10           No  No phone service             DSL            Yes           No               No          No          No              No  Month-to-month               No               Mailed check           29.75        301.9    No
8  7892-POOKP  Female              0     Yes         No      28          Yes               Yes     Fiber optic             No           No              Yes         Yes         Yes             Yes  Month-to-month              Yes           Electronic check          104.80      3046.05   Yes
9  6388-TABGU    Male              0      No        Yes      62          Yes                No             DSL            Yes          Yes               No          No          No              No        One year               No  Bank transfer (automatic)           56.15      3487.95    No

In [268]:
df.shape

(7043, 21)

In [269]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'], dtype='object')

In [270]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [271]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [272]:
# step 4: Check missing values with percentage of each columns
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum()/len(df))*100
})

missing.sort_values(
    by="Percentage",
    ascending=False
)

                  Missing Values  Percentage
customerID                     0         0.0
gender                         0         0.0
SeniorCitizen                  0         0.0
Partner                        0         0.0
Dependents                     0         0.0
tenure                         0         0.0
PhoneService                   0         0.0
MultipleLines                  0         0.0
InternetService                0         0.0
OnlineSecurity                 0         0.0
OnlineBackup                   0         0.0
DeviceProtection               0         0.0
TechSupport                    0         0.0
StreamingTV                    0         0.0
StreamingMovies                0         0.0
Contract                       0         0.0
PaperlessBilling               0         0.0
PaymentMethod                  0         0.0
MonthlyCharges                 0         0.0
TotalCharges                   0         0.0
Churn                          0         0.0

In [273]:
# step 5: Check duplicates 
print(df.duplicated().sum())

0

In [274]:
# step 6: Check statistical summary
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [275]:
df.describe(include='object')

        customerID gender Partner Dependents PhoneService MultipleLines InternetService OnlineSecurity OnlineBackup DeviceProtection TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling     PaymentMethod TotalCharges Churn
count         7043   7043    7043       7043         7043          7043            7043           7043         7043             7043        7043        7043            7043            7043             7043              7043         7043  7043
unique        7043      2       2          2            2             3               3              3            3                3           3           3               3               3                2                 4         6531     2
top     3186-AJIEK   Male      No         No          Yes            No     Fiber optic             No           No               No          No          No              No  Month-to-month              Yes  Electronic check         20.2    No
freq             1   3555    3641       4933         6361          3390            3096           3498         3088             3095        3473        2810            2785            3875             4171              2365           11  5174

In [276]:
# step 7: Check unique values
for column in df.columns:
    print(column)
    print(df[column].nunique())
    print("-"*20)

customerID
7043
--------------------
gender
2
--------------------
SeniorCitizen
2
--------------------
Partner
2
--------------------
Dependents
2
--------------------
tenure
73
--------------------
PhoneService
2
--------------------
MultipleLines
3
--------------------
InternetService
3
--------------------
OnlineSecurity
3
--------------------
OnlineBackup
3
--------------------
DeviceProtection
3
--------------------
TechSupport
3
--------------------
StreamingTV
3
--------------------
StreamingMovies
3
--------------------
Contract
3
--------------------
PaperlessBilling
2
--------------------
PaymentMethod
4
--------------------
MonthlyCharges
1585
--------------------
TotalCharges
6531
--------------------
Churn
2
--------------------

In [277]:
# step 8: Target Values
df['Churn'].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [278]:
# Target values in percentage 
df['Churn'].value_counts(normalize=True)*100

Churn
No     73.463013
Yes    26.536987
Name: proportion, dtype: float64

In [279]:
# step 9: Numerical vs Categorical Columns
numerical_columns = df.select_dtypes(include=np.number).columns.tolist()
categorical_columns = df.select_dtypes(exclude=np.number).columns.tolist()

In [280]:
print("Numerical Features")
print(numerical_columns)
print("-"*40)
print('Categorical Features')
print(categorical_columns)

Numerical Features
['SeniorCitizen', 'tenure', 'MonthlyCharges']
----------------------------------------
Categorical Features
['customerID', 'gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'TotalCharges', 'Churn']

In [281]:
print(df['TotalCharges'].dtype)

object

In [282]:
# Create a dataset summary
summary = pd.DataFrame({
    "Data Type ": df.dtypes,
    "Missing Values": df.isnull().sum(),
    "Unique values": df.nunique()
})

summary

                 Data Type   Missing Values  Unique values
customerID           object               0           7043
gender               object               0              2
SeniorCitizen         int64               0              2
Partner              object               0              2
Dependents           object               0              2
tenure                int64               0             73
PhoneService         object               0              2
MultipleLines        object               0              3
InternetService      object               0              3
OnlineSecurity       object               0              3
OnlineBackup         object               0              3
DeviceProtection     object               0              3
TechSupport          object               0              3
StreamingTV          object               0              3
StreamingMovies      object               0              3
Contract             object               0              3
PaperlessBilling     object               0              2
PaymentMethod        object               0              4
MonthlyCharges      float64               0           1585
TotalCharges         object               0           6531
Churn                object               0              2

## Initial Observations

- Dataset contains 7,043 customer records with 21 features.
- Target variable is `Churn`.
- Mix of numerical and categorical features.
- `TotalCharges` appears to have an incorrect data type.
- Some columns have only two categories and may be label encoded.
- The dataset is slightly imbalanced.

In [283]:
#print(df.dtypes)
print(df.nunique())

customerID          7043
gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
tenure                73
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
MonthlyCharges      1585
TotalCharges        6531
Churn                  2
dtype: int64

In [284]:
print(df['MonthlyCharges'].dtype)

float64

In [285]:
print(df['TotalCharges'].dtype)

object

In [286]:
print(df['Churn'].value_counts())

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [287]:
df["TotalCharges"].head(10)

0      29.85
1     1889.5
2     108.15
3    1840.75
4     151.65
5      820.5
6     1949.4
7      301.9
8    3046.05
9    3487.95
Name: TotalCharges, dtype: object

In [288]:
print((df['TotalCharges'] == " ").sum())

11

This means:
df.isnull().sum() reported 0 missing values.
However, there are 11 blank strings (" ").
These blank strings are hidden missing values.

This is a very common real-world data quality issue.
we will hand these values first.

**Professional Data Cleaning**

In [289]:
# step 1: Replace Blank string with NaN
df['TotalCharges'] = df['TotalCharges'].replace(" ", np.nan)

In [290]:
print((df['TotalCharges'] == " ").sum())

0

In [291]:
# After replacing there is 11 null values in TotalCharges feature.
print(df["TotalCharges"].isnull().sum())

11

In [292]:
# step 2: Convert to Numeric 
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors="coerce")
# The errors="coerce" argument converts any non-numeric values into NaN, 
# which is a professional and safe approach.

In [293]:
# verify data type 
print(df['TotalCharges'].dtype)

float64

In [294]:
# Chech missing values again
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

Now we remove these missing values

In [295]:
df.dropna()

      customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService     MultipleLines InternetService OnlineSecurity OnlineBackup DeviceProtection TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling              PaymentMethod  MonthlyCharges  TotalCharges Churn
0     7590-VHVEG  Female              0     Yes         No       1           No  No phone service             DSL             No          Yes               No          No          No              No  Month-to-month              Yes           Electronic check           29.85         29.85    No
1     5575-GNVDE    Male              0      No         No      34          Yes                No             DSL            Yes           No              Yes          No          No              No        One year               No               Mailed check           56.95       1889.50    No
2     3668-QPYBK    Male              0      No         No       2          Yes                No             DSL            Yes          Yes               No          No          No              No  Month-to-month              Yes               Mailed check           53.85        108.15   Yes
3     7795-CFOCW    Male              0      No         No      45           No  No phone service             DSL            Yes           No              Yes         Yes          No              No        One year               No  Bank transfer (automatic)           42.30       1840.75    No
4     9237-HQITU  Female              0      No         No       2          Yes                No     Fiber optic             No           No               No          No          No              No  Month-to-month              Yes           Electronic check           70.70        151.65   Yes
...          ...     ...            ...     ...        ...     ...          ...               ...             ...            ...          ...              ...         ...         ...             ...             ...              ...                        ...             ...           ...   ...
7038  6840-RESVB    Male              0     Yes        Yes      24          Yes               Yes             DSL            Yes           No              Yes         Yes         Yes             Yes        One year              Yes               Mailed check           84.80       1990.50    No
7039  2234-XADUH  Female              0     Yes        Yes      72          Yes               Yes     Fiber optic             No          Yes              Yes          No         Yes             Yes        One year              Yes    Credit card (automatic)          103.20       7362.90    No
7040  4801-JZAZL  Female              0     Yes        Yes      11           No  No phone service             DSL            Yes           No               No          No          No              No  Month-to-month              Yes           Electronic check           29.60        346.45    No
7041  8361-LTMKD    Male              1     Yes         No       4          Yes               Yes     Fiber optic             No           No               No          No          No              No  Month-to-month              Yes               Mailed check           74.40        306.60   Yes
7042  3186-AJIEK    Male              0      No         No      66          Yes                No     Fiber optic            Yes           No              Yes         Yes         Yes             Yes        Two year              Yes  Bank transfer (automatic)          105.65       6844.50    No

[7032 rows x 21 columns]

In [303]:
# Again verify the dataset size
df.shape

(7043, 21)

In [302]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

missing values still exist so we fill these values with 
df["TotalCharges"] = df["TotalCharges"].fillna(0)

In [298]:
df["TotalCharges"] = df["TotalCharges"].fillna(0)

In [299]:
# verify
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [300]:
# Again verify
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

**Step 5: Now onward we will prepare data for training**

In [305]:
# Remove customerID because this feature has no predictive value.
df.drop(columns='customerID', inplace=True)
df.shape

(7043, 20)

**Separate Features and Target**

In [306]:
X = df.drop("Churn", axis=1)
y = df["Churn"]

**Identify Feature Types**

In [307]:
numerical_features = X.select_dtypes(include=["int64", "float64"]).columns.tolist()

categorical_features = X.select_dtypes(include=["object"]).columns.tolist()

In [308]:
print("Numerical Features:")
print(numerical_features)

print()

print("Categorical Features:")
print(categorical_features)

Numerical Features:
['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']

Categorical Features:
['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']